### ISSUE TITLE
Links broken on pkgdown site

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiralci#13]
Not completely sure how legit we are trying to make `admiralci` pkgdown site, but someone from gsk was taking a look at it and found that most of the links were broken.

![image](https://user-images.githubusercontent.com/10111024/191254044-f0d5da26-2951-4ea1-bde6-8434d751e878.png)

Shall we fix these?

**Comment by zdz2101** [comment]
Broken on the [pharmaverse website](https://pharmaverse.github.io/admiralci/main/) but not on the readme of the [github page](https://github.com/pharmaverse/admiralci) 

Looks like its because the RMD uses "." to grab the home URL:  `(./.github/workflows/check-templates.yml)` 

A solution to ensure it works in both places is to find+replace these instances of `./.github/workflows` with `https://github.com/pharmaverse/admiralci/blob/main/.github/workflows/`

**Comment by galachad** [comment]
I think best option will be to to tweak links in html file.  It's possible to prototype the pkgdown function but it will be nice to have this functionality in pkgdown as it allow much more customisation. I create [pr](https://github.com/r-lib/pkgdown/pull/2256) to pkgdown so let's wait for discussion there.

This is example of tweak function that fix urls ends with `.yml`. We can also create more advance rules that will work correctly with different version/branches/release. 

```r
setHook("UserHook::pkgdown::tweak_page", function(...) {
  html <- ..1

  links <- xml2::xml_find_all(html, ".//a")
  if (length(links) == 0)
    return(invisible())

  hrefs <- xml2::xml_attr(links, "href")
  needs_tweak <- grepl("\\.yml$", hrefs) & xml2::url_parse(hrefs)$scheme == ""

  fix_links <- function(x) {
    x <- gsub("^./", "", x)
    x <- paste0("https://github.com/pharmaverse/admiralci/blob/HEAD/", x)
  }

  if (any(needs_tweak)) {
    purrr::walk2(
      links[needs_tweak],
      fix_links(hrefs[needs_tweak]),
      xml2::xml_set_attr,
      attr = "href"
    )
  }

  invisible()
})
```
